[GLOBAL]
pants_version = "2.8.0.dev5"
backend_packages.add = [
  "pants.backend.project_info",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  # "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = ['/']

[python-setup]
interpreter_constraints = ["CPython>=3.8,<3.9"]