name: Docker FOSS publish toolchain

on: [push]

jobs:
    build-push:
        name: Build & push Docker release image
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Update git SHA
              run: echo "GIT_SHA = '${GITHUB_SHA}'" > posthog/gitsha.py
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            # - name: Login to DockerHub
            #
            #   uses: docker/login-action@v1
            #   with:
            #       username: ${{ secrets.DOCKERHUB_USERNAME }}
            #       password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build release
              id: docker-release
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: false
                  tags: |
                      asherf/posthog-foss:latest-release
                      asherf/posthog-foss:release-${{ env.TAG_NAME  }}

            # - name: Image digest
            #   run: |
            #       echo "Pushed release: ${{ steps.docker-release.outputs.digest }}"
